name: Xandra frontend production

on:
  push:
    branches:
      - 'main'

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Xandra frontend image
        run: docker build -t xandra767/remix-front:latest . -f Dockerfile.prod

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Xandra frontend image
        run: docker image push xandra767/remix-front:latest

      - name: Deploy Xandra frontend via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            rm -rf remix-front
            git clone git@github.com:Xandra767/remix-front.git
            cd ./remix-front
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker-compose -f docker-compose-prod.yml down
            docker image rm xandra767/remix-front:latest
            docker-compose -f docker-compose-prod.yml up -d --build
            cd ..
            rm -rf remix-front
